using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Fable3LUADecompiler
{
    class Fable3OPCodes
    {
        public static Dictionary<int, LuaOpCode.OpCodes> OPCodeTable = new Dictionary<int, LuaOpCode.OpCodes>()
        {
            // Same opcode table as bo3, they just dont have the shift left, right and bitwise operators
            { 0,         LuaOpCode.OpCodes.HKS_OPCODE_GETFIELD },
            { 1,         LuaOpCode.OpCodes.HKS_OPCODE_TEST },
            { 2,         LuaOpCode.OpCodes.HKS_OPCODE_CALL_I },
            { 3,         LuaOpCode.OpCodes.HKS_OPCODE_CALL_C },
            { 4,         LuaOpCode.OpCodes.HKS_OPCODE_EQ },
            { 5,         LuaOpCode.OpCodes.HKS_OPCODE_EQ_BK },
            { 6,         LuaOpCode.OpCodes.HKS_OPCODE_GETGLOBAL },
            { 7,         LuaOpCode.OpCodes.HKS_OPCODE_MOVE },
            { 8,         LuaOpCode.OpCodes.HKS_OPCODE_SELF },
            { 9,         LuaOpCode.OpCodes.HKS_OPCODE_RETURN },
            { 10,        LuaOpCode.OpCodes.HKS_OPCODE_GETTABLE_S },
            { 11,        LuaOpCode.OpCodes.HKS_OPCODE_GETTABLE_N },
            { 12,        LuaOpCode.OpCodes.HKS_OPCODE_GETTABLE },
            { 13,        LuaOpCode.OpCodes.HKS_OPCODE_LOADBOOL },
            { 14,        LuaOpCode.OpCodes.HKS_OPCODE_TFORLOOP },
            { 15,        LuaOpCode.OpCodes.HKS_OPCODE_SETFIELD },
            { 16,        LuaOpCode.OpCodes.HKS_OPCODE_SETTABLE_S },
            { 17,        LuaOpCode.OpCodes.HKS_OPCODE_SETTABLE_S_BK },
            { 18,        LuaOpCode.OpCodes.HKS_OPCODE_SETTABLE_N },
            { 19,        LuaOpCode.OpCodes.HKS_OPCODE_SETTABLE_N_BK },
            { 20,        LuaOpCode.OpCodes.HKS_OPCODE_SETTABLE },
            { 21,        LuaOpCode.OpCodes.HKS_OPCODE_SETTABLE_BK },
            { 22,        LuaOpCode.OpCodes.HKS_OPCODE_TAILCALL_I },
            { 23,        LuaOpCode.OpCodes.HKS_OPCODE_TAILCALL_C },
            { 24,        LuaOpCode.OpCodes.HKS_OPCODE_TAILCALL_M },
            { 25,        LuaOpCode.OpCodes.HKS_OPCODE_LOADK },
            { 26,        LuaOpCode.OpCodes.HKS_OPCODE_LOADNIL },
            { 27,        LuaOpCode.OpCodes.HKS_OPCODE_SETGLOBAL },
            { 28,        LuaOpCode.OpCodes.HKS_OPCODE_JMP },
            { 29,        LuaOpCode.OpCodes.HKS_OPCODE_CALL_M },
            { 30,        LuaOpCode.OpCodes.HKS_OPCODE_CALL },
            { 31,        LuaOpCode.OpCodes.HKS_OPCODE_TAILCALL },
            { 32,        LuaOpCode.OpCodes.HKS_OPCODE_GETUPVAL },
            { 33,        LuaOpCode.OpCodes.HKS_OPCODE_SETUPVAL },
            { 34,        LuaOpCode.OpCodes.HKS_OPCODE_ADD },
            { 35,        LuaOpCode.OpCodes.HKS_OPCODE_ADD_BK },
            { 36,        LuaOpCode.OpCodes.HKS_OPCODE_SUB },
            { 37,        LuaOpCode.OpCodes.HKS_OPCODE_SUB_BK },
            { 38,        LuaOpCode.OpCodes.HKS_OPCODE_MUL },
            { 39,        LuaOpCode.OpCodes.HKS_OPCODE_MUL_BK },
            { 40,        LuaOpCode.OpCodes.HKS_OPCODE_DIV },
            { 41,        LuaOpCode.OpCodes.HKS_OPCODE_DIV_BK },
            { 42,        LuaOpCode.OpCodes.HKS_OPCODE_MOD },
            { 43,        LuaOpCode.OpCodes.HKS_OPCODE_MOD_BK },
            { 44,        LuaOpCode.OpCodes.HKS_OPCODE_POW },
            { 45,        LuaOpCode.OpCodes.HKS_OPCODE_POW_BK },
            { 46,        LuaOpCode.OpCodes.HKS_OPCODE_NEWTABLE },
            { 47,        LuaOpCode.OpCodes.HKS_OPCODE_UNM },
            { 48,        LuaOpCode.OpCodes.HKS_OPCODE_NOT },
            { 49,        LuaOpCode.OpCodes.HKS_OPCODE_LEN },
            { 50,        LuaOpCode.OpCodes.HKS_OPCODE_LT },
            { 51,        LuaOpCode.OpCodes.HKS_OPCODE_LT_BK },
            { 52,        LuaOpCode.OpCodes.HKS_OPCODE_LE },
            { 53,        LuaOpCode.OpCodes.HKS_OPCODE_LE_BK },
            { 54,        LuaOpCode.OpCodes.HKS_OPCODE_CONCAT },
            { 55,        LuaOpCode.OpCodes.HKS_OPCODE_TESTSET },
            { 56,        LuaOpCode.OpCodes.HKS_OPCODE_FORPREP },
            { 57,        LuaOpCode.OpCodes.HKS_OPCODE_FORLOOP },
            { 58,        LuaOpCode.OpCodes.HKS_OPCODE_SETLIST },
            { 59,        LuaOpCode.OpCodes.HKS_OPCODE_CLOSE },
            { 60,        LuaOpCode.OpCodes.HKS_OPCODE_CLOSURE },
            { 61,        LuaOpCode.OpCodes.HKS_OPCODE_VARARG },
            { 62,        LuaOpCode.OpCodes.HKS_OPCODE_TAILCALL_I_R1 },
            { 63,        LuaOpCode.OpCodes.HKS_OPCODE_CALL_I_R1 },
            { 64,        LuaOpCode.OpCodes.HKS_OPCODE_SETUPVAL_R1 },
            { 65,        LuaOpCode.OpCodes.HKS_OPCODE_TEST_R1 },
            { 66,        LuaOpCode.OpCodes.HKS_OPCODE_NOT_R1 },
            { 67,        LuaOpCode.OpCodes.HKS_OPCODE_GETFIELD_R1 },
            { 68,        LuaOpCode.OpCodes.HKS_OPCODE_SETFIELD_R1 },
            { 69,        LuaOpCode.OpCodes.HKS_OPCODE_NEWSTRUCT },
            { 70,        LuaOpCode.OpCodes.HKS_OPCODE_DATA },
            { 71,        LuaOpCode.OpCodes.HKS_OPCODE_SETSLOTN },
            { 72,        LuaOpCode.OpCodes.HKS_OPCODE_SETSLOTI },
            { 73,        LuaOpCode.OpCodes.HKS_OPCODE_SETSLOT },
            { 74,        LuaOpCode.OpCodes.HKS_OPCODE_SETSLOTS },
            { 75,        LuaOpCode.OpCodes.HKS_OPCODE_SETSLOTMT },
            { 76,        LuaOpCode.OpCodes.HKS_OPCODE_CHECKTYPE },
            { 77,        LuaOpCode.OpCodes.HKS_OPCODE_CHECKTYPES },
            { 78,        LuaOpCode.OpCodes.HKS_OPCODE_GETSLOT },
            { 79,        LuaOpCode.OpCodes.HKS_OPCODE_GETSLOTMT },
            { 80,        LuaOpCode.OpCodes.HKS_OPCODE_SELFSLOT },
            { 81,        LuaOpCode.OpCodes.HKS_OPCODE_SELFSLOTMT },
            { 82,        LuaOpCode.OpCodes.HKS_OPCODE_GETFIELD_MM },
            { 83,        LuaOpCode.OpCodes.HKS_OPCODE_CHECKTYPE_D },
            { 84,        LuaOpCode.OpCodes.HKS_OPCODE_GETSLOT_D },
            { 85,        LuaOpCode.OpCodes.HKS_OPCODE_GETGLOBAL_MEM },
            { 86,        LuaOpCode.OpCodes.HKS_OPCODE_MAX },
        };
    }
}
